---
title: 'Fig.4.4 - Pearl 2009'
author: "shs"
date: "21 3 2019"
output: 
  pdf_document:
    highlight: monochrome
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r, include = FALSE}
library(tidyverse)
options(tibble.print_min = 250)
knitr::knit_engines$set(data2 = function(options) {
  assign("text", options$code, envir = globalenv())
  #NULL
})
```


```{r, include = FALSE}
library(magrittr)
library(causaleffect)
library(igraph)
#library(googledrive)
#library(rlang)
#library(tidyverse)
#library(data.tree)
#library(collapsibleTree)
#library(lobstr)

doll  <- magrittr::use_series
options(tibble.print_min = 100)

# --------------------------------------------
# Smoking:
G     <- parse.graphml("C:\\Users\\shs\\Desktop\\graph_ed\\2.graphml")

sils  <- causaleffect:::latent.projection(G, "gene")

ce1   <- causal.effect(y = "Y", 
                       x = "X", 
                       z = NULL, 
                       G = sils, expr = TRUE, steps = TRUE, primes = T)

```


```{r, results='asis'}
cat(paste0("$$", ce1$P, "$$"))
```


```{data2, include = FALSE}
<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill-opacity="1" color-rendering="auto" color-interpolation="auto" text-rendering="auto" stroke="black" stroke-linecap="square" width="510" stroke-miterlimit="10" shape-rendering="auto" stroke-opacity="1" fill="black" stroke-dasharray="none" font-weight="normal" stroke-width="1" height="540" font-family="'Dialog'" font-style="normal" stroke-linejoin="miter" font-size="12px" stroke-dashoffset="0" image-rendering="auto">
  <!--Generated by ySVG 2.5-->
  <defs id="genericDefs"/>
  <g>
    <defs id="defs1">
      <clipPath clipPathUnits="userSpaceOnUse" id="clipPath1">
        <path d="M0 0 L510 0 L510 540 L0 540 L0 0 Z"/>
      </clipPath>
      <clipPath clipPathUnits="userSpaceOnUse" id="clipPath2">
        <path d="M60 60 L570 60 L570 600 L60 600 L60 60 Z"/>
      </clipPath>
    </defs>
    <g fill="white" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="translate(-60,-60)" stroke="white">
      <rect x="60" width="510" height="540" y="60" clip-path="url(#clipPath2)" stroke="none"/>
    </g>
    <g fill="gray" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" stroke="gray">
      <line y2="-29" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="-31"/>
      <line y2="-30" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="-30"/>
      <line y2="1" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="-1"/>
      <line y2="0" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="0"/>
      <line y2="31" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="29"/>
      <line y2="30" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="30"/>
      <line y2="61" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="59"/>
      <line y2="60" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="60"/>
      <line y2="91" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="89"/>
      <line y2="90" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="90"/>
      <line y2="121" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="119"/>
      <line y2="120" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="120"/>
      <line y2="151" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="149"/>
      <line y2="150" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="150"/>
      <line y2="181" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="179"/>
      <line y2="180" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="180"/>
      <line y2="211" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="209"/>
      <line y2="210" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="210"/>
      <line y2="241" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="239"/>
      <line y2="240" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="240"/>
      <line y2="271" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="269"/>
      <line y2="270" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="270"/>
      <line y2="301" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="299"/>
      <line y2="300" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="300"/>
      <line y2="331" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="329"/>
      <line y2="330" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="330"/>
      <line y2="361" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="359"/>
      <line y2="360" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="360"/>
      <line y2="391" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="389"/>
      <line y2="390" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="390"/>
      <line y2="421" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="419"/>
      <line y2="420" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="420"/>
      <line y2="451" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="449"/>
      <line y2="450" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="450"/>
      <line y2="481" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="479"/>
      <line y2="480" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="480"/>
      <line y2="511" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="509"/>
      <line y2="510" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="510"/>
      <line y2="541" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="539"/>
      <line y2="540" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="540"/>
      <line y2="571" fill="none" x1="-30" clip-path="url(#clipPath1)" x2="-30" y1="569"/>
      <line y2="570" fill="none" x1="-31" clip-path="url(#clipPath1)" x2="-29" y1="570"/>
      <line y2="-29" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="-31"/>
      <line y2="-30" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="-30"/>
      <line y2="1" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="-1"/>
      <line y2="0" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="0"/>
      <line y2="31" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="29"/>
      <line y2="30" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="30"/>
      <line y2="61" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="59"/>
      <line y2="60" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="60"/>
      <line y2="91" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="89"/>
      <line y2="90" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="90"/>
      <line y2="121" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="119"/>
      <line y2="120" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="120"/>
      <line y2="151" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="149"/>
      <line y2="150" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="150"/>
      <line y2="181" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="179"/>
      <line y2="180" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="180"/>
      <line y2="211" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="209"/>
      <line y2="210" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="210"/>
      <line y2="241" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="239"/>
      <line y2="240" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="240"/>
      <line y2="271" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="269"/>
      <line y2="270" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="270"/>
      <line y2="301" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="299"/>
      <line y2="300" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="300"/>
      <line y2="331" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="329"/>
      <line y2="330" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="330"/>
      <line y2="361" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="359"/>
      <line y2="360" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="360"/>
      <line y2="391" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="389"/>
      <line y2="390" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="390"/>
      <line y2="421" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="419"/>
      <line y2="420" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="420"/>
      <line y2="451" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="449"/>
      <line y2="450" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="450"/>
      <line y2="481" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="479"/>
      <line y2="480" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="480"/>
      <line y2="511" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="509"/>
      <line y2="510" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="510"/>
      <line y2="541" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="539"/>
      <line y2="540" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="540"/>
      <line y2="571" fill="none" x1="0" clip-path="url(#clipPath1)" x2="0" y1="569"/>
      <line y2="570" fill="none" x1="-1" clip-path="url(#clipPath1)" x2="1" y1="570"/>
      <line y2="-29" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="-31"/>
      <line y2="-30" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="-30"/>
      <line y2="1" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="-1"/>
      <line y2="0" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="0"/>
      <line y2="31" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="29"/>
      <line y2="30" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="30"/>
      <line y2="61" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="59"/>
      <line y2="60" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="60"/>
      <line y2="91" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="89"/>
      <line y2="90" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="90"/>
      <line y2="121" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="119"/>
      <line y2="120" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="120"/>
      <line y2="151" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="149"/>
      <line y2="150" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="150"/>
      <line y2="181" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="179"/>
      <line y2="180" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="180"/>
      <line y2="211" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="209"/>
      <line y2="210" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="210"/>
      <line y2="241" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="239"/>
      <line y2="240" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="240"/>
      <line y2="271" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="269"/>
      <line y2="270" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="270"/>
      <line y2="301" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="299"/>
      <line y2="300" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="300"/>
      <line y2="331" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="329"/>
      <line y2="330" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="330"/>
      <line y2="361" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="359"/>
      <line y2="360" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="360"/>
      <line y2="391" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="389"/>
      <line y2="390" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="390"/>
      <line y2="421" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="419"/>
      <line y2="420" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="420"/>
      <line y2="451" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="449"/>
      <line y2="450" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="450"/>
      <line y2="481" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="479"/>
      <line y2="480" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="480"/>
      <line y2="511" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="509"/>
      <line y2="510" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="510"/>
      <line y2="541" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="539"/>
      <line y2="540" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="540"/>
      <line y2="571" fill="none" x1="30" clip-path="url(#clipPath1)" x2="30" y1="569"/>
      <line y2="570" fill="none" x1="29" clip-path="url(#clipPath1)" x2="31" y1="570"/>
      <line y2="-29" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="-31"/>
      <line y2="-30" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="-30"/>
      <line y2="1" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="-1"/>
      <line y2="0" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="0"/>
      <line y2="31" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="29"/>
      <line y2="30" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="30"/>
      <line y2="61" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="59"/>
      <line y2="60" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="60"/>
      <line y2="91" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="89"/>
      <line y2="90" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="90"/>
      <line y2="121" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="119"/>
      <line y2="120" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="120"/>
      <line y2="151" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="149"/>
      <line y2="150" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="150"/>
      <line y2="181" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="179"/>
      <line y2="180" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="180"/>
      <line y2="211" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="209"/>
      <line y2="210" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="210"/>
      <line y2="241" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="239"/>
      <line y2="240" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="240"/>
      <line y2="271" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="269"/>
      <line y2="270" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="270"/>
      <line y2="301" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="299"/>
      <line y2="300" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="300"/>
      <line y2="331" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="329"/>
      <line y2="330" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="330"/>
      <line y2="361" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="359"/>
      <line y2="360" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="360"/>
      <line y2="391" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="389"/>
      <line y2="390" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="390"/>
      <line y2="421" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="419"/>
      <line y2="420" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="420"/>
      <line y2="451" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="449"/>
      <line y2="450" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="450"/>
      <line y2="481" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="479"/>
      <line y2="480" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="480"/>
      <line y2="511" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="509"/>
      <line y2="510" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="510"/>
      <line y2="541" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="539"/>
      <line y2="540" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="540"/>
      <line y2="571" fill="none" x1="60" clip-path="url(#clipPath1)" x2="60" y1="569"/>
      <line y2="570" fill="none" x1="59" clip-path="url(#clipPath1)" x2="61" y1="570"/>
      <line y2="-29" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="-31"/>
      <line y2="-30" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="-30"/>
      <line y2="1" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="-1"/>
      <line y2="0" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="0"/>
      <line y2="31" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="29"/>
      <line y2="30" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="30"/>
      <line y2="61" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="59"/>
      <line y2="60" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="60"/>
      <line y2="91" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="89"/>
      <line y2="90" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="90"/>
      <line y2="121" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="119"/>
      <line y2="120" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="120"/>
      <line y2="151" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="149"/>
      <line y2="150" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="150"/>
      <line y2="181" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="179"/>
      <line y2="180" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="180"/>
      <line y2="211" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="209"/>
      <line y2="210" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="210"/>
      <line y2="241" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="239"/>
      <line y2="240" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="240"/>
      <line y2="271" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="269"/>
      <line y2="270" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="270"/>
      <line y2="301" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="299"/>
      <line y2="300" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="300"/>
      <line y2="331" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="329"/>
      <line y2="330" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="330"/>
      <line y2="361" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="359"/>
      <line y2="360" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="360"/>
      <line y2="391" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="389"/>
      <line y2="390" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="390"/>
      <line y2="421" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="419"/>
      <line y2="420" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="420"/>
      <line y2="451" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="449"/>
      <line y2="450" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="450"/>
      <line y2="481" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="479"/>
      <line y2="480" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="480"/>
      <line y2="511" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="509"/>
      <line y2="510" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="510"/>
      <line y2="541" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="539"/>
      <line y2="540" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="540"/>
      <line y2="571" fill="none" x1="90" clip-path="url(#clipPath1)" x2="90" y1="569"/>
      <line y2="570" fill="none" x1="89" clip-path="url(#clipPath1)" x2="91" y1="570"/>
      <line y2="-29" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="-31"/>
      <line y2="-30" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="-30"/>
      <line y2="1" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="-1"/>
      <line y2="0" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="0"/>
      <line y2="31" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="29"/>
      <line y2="30" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="30"/>
      <line y2="61" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="59"/>
      <line y2="60" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="60"/>
      <line y2="91" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="89"/>
      <line y2="90" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="90"/>
      <line y2="121" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="119"/>
      <line y2="120" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="120"/>
      <line y2="151" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="149"/>
      <line y2="150" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="150"/>
      <line y2="181" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="179"/>
      <line y2="180" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="180"/>
      <line y2="211" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="209"/>
      <line y2="210" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="210"/>
      <line y2="241" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="239"/>
      <line y2="240" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="240"/>
      <line y2="271" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="269"/>
      <line y2="270" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="270"/>
      <line y2="301" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="299"/>
      <line y2="300" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="300"/>
      <line y2="331" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="329"/>
      <line y2="330" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="330"/>
      <line y2="361" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="359"/>
      <line y2="360" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="360"/>
      <line y2="391" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="389"/>
      <line y2="390" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="390"/>
      <line y2="421" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="419"/>
      <line y2="420" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="420"/>
      <line y2="451" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="449"/>
      <line y2="450" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="450"/>
      <line y2="481" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="479"/>
      <line y2="480" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="480"/>
      <line y2="511" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="509"/>
      <line y2="510" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="510"/>
      <line y2="541" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="539"/>
      <line y2="540" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="540"/>
      <line y2="571" fill="none" x1="120" clip-path="url(#clipPath1)" x2="120" y1="569"/>
      <line y2="570" fill="none" x1="119" clip-path="url(#clipPath1)" x2="121" y1="570"/>
      <line y2="-29" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="-31"/>
      <line y2="-30" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="-30"/>
      <line y2="1" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="-1"/>
      <line y2="0" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="0"/>
      <line y2="31" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="29"/>
      <line y2="30" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="30"/>
      <line y2="61" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="59"/>
      <line y2="60" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="60"/>
      <line y2="91" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="89"/>
      <line y2="90" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="90"/>
      <line y2="121" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="119"/>
      <line y2="120" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="120"/>
      <line y2="151" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="149"/>
      <line y2="150" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="150"/>
      <line y2="181" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="179"/>
      <line y2="180" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="180"/>
      <line y2="211" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="209"/>
      <line y2="210" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="210"/>
      <line y2="241" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="239"/>
      <line y2="240" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="240"/>
      <line y2="271" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="269"/>
      <line y2="270" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="270"/>
      <line y2="301" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="299"/>
      <line y2="300" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="300"/>
      <line y2="331" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="329"/>
      <line y2="330" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="330"/>
      <line y2="361" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="359"/>
      <line y2="360" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="360"/>
      <line y2="391" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="389"/>
      <line y2="390" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="390"/>
      <line y2="421" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="419"/>
      <line y2="420" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="420"/>
      <line y2="451" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="449"/>
      <line y2="450" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="450"/>
      <line y2="481" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="479"/>
      <line y2="480" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="480"/>
      <line y2="511" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="509"/>
      <line y2="510" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="510"/>
      <line y2="541" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="539"/>
      <line y2="540" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="540"/>
      <line y2="571" fill="none" x1="150" clip-path="url(#clipPath1)" x2="150" y1="569"/>
      <line y2="570" fill="none" x1="149" clip-path="url(#clipPath1)" x2="151" y1="570"/>
      <line y2="-29" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="-31"/>
      <line y2="-30" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="-30"/>
      <line y2="1" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="-1"/>
      <line y2="0" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="0"/>
      <line y2="31" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="29"/>
      <line y2="30" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="30"/>
      <line y2="61" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="59"/>
      <line y2="60" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="60"/>
      <line y2="91" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="89"/>
      <line y2="90" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="90"/>
      <line y2="121" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="119"/>
      <line y2="120" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="120"/>
      <line y2="151" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="149"/>
      <line y2="150" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="150"/>
      <line y2="181" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="179"/>
      <line y2="180" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="180"/>
      <line y2="211" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="209"/>
      <line y2="210" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="210"/>
      <line y2="241" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="239"/>
      <line y2="240" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="240"/>
      <line y2="271" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="269"/>
      <line y2="270" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="270"/>
      <line y2="301" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="299"/>
      <line y2="300" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="300"/>
      <line y2="331" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="329"/>
      <line y2="330" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="330"/>
      <line y2="361" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="359"/>
      <line y2="360" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="360"/>
      <line y2="391" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="389"/>
      <line y2="390" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="390"/>
      <line y2="421" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="419"/>
      <line y2="420" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="420"/>
      <line y2="451" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="449"/>
      <line y2="450" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="450"/>
      <line y2="481" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="479"/>
      <line y2="480" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="480"/>
      <line y2="511" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="509"/>
      <line y2="510" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="510"/>
      <line y2="541" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="539"/>
      <line y2="540" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="540"/>
      <line y2="571" fill="none" x1="180" clip-path="url(#clipPath1)" x2="180" y1="569"/>
      <line y2="570" fill="none" x1="179" clip-path="url(#clipPath1)" x2="181" y1="570"/>
      <line y2="-29" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="-31"/>
      <line y2="-30" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="-30"/>
      <line y2="1" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="-1"/>
      <line y2="0" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="0"/>
      <line y2="31" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="29"/>
      <line y2="30" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="30"/>
      <line y2="61" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="59"/>
      <line y2="60" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="60"/>
      <line y2="91" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="89"/>
      <line y2="90" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="90"/>
      <line y2="121" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="119"/>
      <line y2="120" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="120"/>
      <line y2="151" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="149"/>
      <line y2="150" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="150"/>
      <line y2="181" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="179"/>
      <line y2="180" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="180"/>
      <line y2="211" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="209"/>
      <line y2="210" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="210"/>
      <line y2="241" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="239"/>
      <line y2="240" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="240"/>
      <line y2="271" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="269"/>
      <line y2="270" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="270"/>
      <line y2="301" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="299"/>
      <line y2="300" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="300"/>
      <line y2="331" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="329"/>
      <line y2="330" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="330"/>
      <line y2="361" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="359"/>
      <line y2="360" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="360"/>
      <line y2="391" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="389"/>
      <line y2="390" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="390"/>
      <line y2="421" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="419"/>
      <line y2="420" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="420"/>
      <line y2="451" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="449"/>
      <line y2="450" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="450"/>
      <line y2="481" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="479"/>
      <line y2="480" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="480"/>
      <line y2="511" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="509"/>
      <line y2="510" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="510"/>
      <line y2="541" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="539"/>
      <line y2="540" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="540"/>
      <line y2="571" fill="none" x1="210" clip-path="url(#clipPath1)" x2="210" y1="569"/>
      <line y2="570" fill="none" x1="209" clip-path="url(#clipPath1)" x2="211" y1="570"/>
      <line y2="-29" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="-31"/>
      <line y2="-30" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="-30"/>
      <line y2="1" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="-1"/>
      <line y2="0" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="0"/>
      <line y2="31" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="29"/>
      <line y2="30" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="30"/>
      <line y2="61" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="59"/>
      <line y2="60" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="60"/>
      <line y2="91" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="89"/>
      <line y2="90" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="90"/>
      <line y2="121" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="119"/>
      <line y2="120" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="120"/>
      <line y2="151" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="149"/>
      <line y2="150" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="150"/>
      <line y2="181" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="179"/>
      <line y2="180" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="180"/>
      <line y2="211" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="209"/>
      <line y2="210" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="210"/>
      <line y2="241" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="239"/>
      <line y2="240" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="240"/>
      <line y2="271" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="269"/>
      <line y2="270" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="270"/>
      <line y2="301" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="299"/>
      <line y2="300" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="300"/>
      <line y2="331" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="329"/>
      <line y2="330" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="330"/>
      <line y2="361" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="359"/>
      <line y2="360" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="360"/>
      <line y2="391" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="389"/>
      <line y2="390" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="390"/>
      <line y2="421" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="419"/>
      <line y2="420" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="420"/>
      <line y2="451" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="449"/>
      <line y2="450" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="450"/>
      <line y2="481" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="479"/>
      <line y2="480" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="480"/>
      <line y2="511" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="509"/>
      <line y2="510" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="510"/>
      <line y2="541" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="539"/>
      <line y2="540" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="540"/>
      <line y2="571" fill="none" x1="240" clip-path="url(#clipPath1)" x2="240" y1="569"/>
      <line y2="570" fill="none" x1="239" clip-path="url(#clipPath1)" x2="241" y1="570"/>
      <line y2="-29" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="-31"/>
      <line y2="-30" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="-30"/>
      <line y2="1" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="-1"/>
      <line y2="0" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="0"/>
      <line y2="31" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="29"/>
      <line y2="30" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="30"/>
      <line y2="61" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="59"/>
      <line y2="60" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="60"/>
      <line y2="91" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="89"/>
      <line y2="90" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="90"/>
      <line y2="121" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="119"/>
      <line y2="120" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="120"/>
      <line y2="151" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="149"/>
      <line y2="150" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="150"/>
      <line y2="181" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="179"/>
      <line y2="180" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="180"/>
      <line y2="211" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="209"/>
      <line y2="210" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="210"/>
      <line y2="241" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="239"/>
      <line y2="240" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="240"/>
      <line y2="271" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="269"/>
      <line y2="270" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="270"/>
      <line y2="301" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="299"/>
      <line y2="300" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="300"/>
      <line y2="331" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="329"/>
      <line y2="330" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="330"/>
      <line y2="361" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="359"/>
      <line y2="360" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="360"/>
      <line y2="391" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="389"/>
      <line y2="390" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="390"/>
      <line y2="421" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="419"/>
      <line y2="420" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="420"/>
      <line y2="451" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="449"/>
      <line y2="450" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="450"/>
      <line y2="481" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="479"/>
      <line y2="480" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="480"/>
      <line y2="511" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="509"/>
      <line y2="510" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="510"/>
      <line y2="541" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="539"/>
      <line y2="540" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="540"/>
      <line y2="571" fill="none" x1="270" clip-path="url(#clipPath1)" x2="270" y1="569"/>
      <line y2="570" fill="none" x1="269" clip-path="url(#clipPath1)" x2="271" y1="570"/>
      <line y2="-29" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="-31"/>
      <line y2="-30" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="-30"/>
      <line y2="1" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="-1"/>
      <line y2="0" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="0"/>
      <line y2="31" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="29"/>
      <line y2="30" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="30"/>
      <line y2="61" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="59"/>
      <line y2="60" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="60"/>
      <line y2="91" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="89"/>
      <line y2="90" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="90"/>
      <line y2="121" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="119"/>
      <line y2="120" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="120"/>
      <line y2="151" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="149"/>
      <line y2="150" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="150"/>
      <line y2="181" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="179"/>
      <line y2="180" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="180"/>
      <line y2="211" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="209"/>
      <line y2="210" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="210"/>
      <line y2="241" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="239"/>
      <line y2="240" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="240"/>
      <line y2="271" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="269"/>
      <line y2="270" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="270"/>
      <line y2="301" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="299"/>
      <line y2="300" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="300"/>
      <line y2="331" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="329"/>
      <line y2="330" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="330"/>
      <line y2="361" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="359"/>
      <line y2="360" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="360"/>
      <line y2="391" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="389"/>
      <line y2="390" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="390"/>
      <line y2="421" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="419"/>
      <line y2="420" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="420"/>
      <line y2="451" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="449"/>
      <line y2="450" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="450"/>
      <line y2="481" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="479"/>
      <line y2="480" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="480"/>
      <line y2="511" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="509"/>
      <line y2="510" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="510"/>
      <line y2="541" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="539"/>
      <line y2="540" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="540"/>
      <line y2="571" fill="none" x1="300" clip-path="url(#clipPath1)" x2="300" y1="569"/>
      <line y2="570" fill="none" x1="299" clip-path="url(#clipPath1)" x2="301" y1="570"/>
      <line y2="-29" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="-31"/>
      <line y2="-30" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="-30"/>
      <line y2="1" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="-1"/>
      <line y2="0" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="0"/>
      <line y2="31" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="29"/>
      <line y2="30" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="30"/>
      <line y2="61" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="59"/>
      <line y2="60" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="60"/>
      <line y2="91" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="89"/>
      <line y2="90" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="90"/>
      <line y2="121" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="119"/>
      <line y2="120" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="120"/>
      <line y2="151" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="149"/>
      <line y2="150" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="150"/>
      <line y2="181" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="179"/>
      <line y2="180" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="180"/>
      <line y2="211" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="209"/>
      <line y2="210" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="210"/>
      <line y2="241" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="239"/>
      <line y2="240" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="240"/>
      <line y2="271" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="269"/>
      <line y2="270" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="270"/>
      <line y2="301" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="299"/>
      <line y2="300" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="300"/>
      <line y2="331" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="329"/>
      <line y2="330" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="330"/>
      <line y2="361" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="359"/>
      <line y2="360" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="360"/>
      <line y2="391" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="389"/>
      <line y2="390" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="390"/>
      <line y2="421" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="419"/>
      <line y2="420" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="420"/>
      <line y2="451" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="449"/>
      <line y2="450" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="450"/>
      <line y2="481" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="479"/>
      <line y2="480" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="480"/>
      <line y2="511" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="509"/>
      <line y2="510" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="510"/>
      <line y2="541" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="539"/>
      <line y2="540" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="540"/>
      <line y2="571" fill="none" x1="330" clip-path="url(#clipPath1)" x2="330" y1="569"/>
      <line y2="570" fill="none" x1="329" clip-path="url(#clipPath1)" x2="331" y1="570"/>
      <line y2="-29" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="-31"/>
      <line y2="-30" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="-30"/>
      <line y2="1" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="-1"/>
      <line y2="0" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="0"/>
      <line y2="31" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="29"/>
      <line y2="30" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="30"/>
      <line y2="61" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="59"/>
      <line y2="60" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="60"/>
      <line y2="91" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="89"/>
      <line y2="90" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="90"/>
      <line y2="121" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="119"/>
      <line y2="120" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="120"/>
      <line y2="151" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="149"/>
      <line y2="150" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="150"/>
      <line y2="181" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="179"/>
      <line y2="180" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="180"/>
      <line y2="211" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="209"/>
      <line y2="210" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="210"/>
      <line y2="241" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="239"/>
      <line y2="240" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="240"/>
      <line y2="271" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="269"/>
      <line y2="270" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="270"/>
      <line y2="301" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="299"/>
      <line y2="300" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="300"/>
      <line y2="331" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="329"/>
      <line y2="330" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="330"/>
      <line y2="361" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="359"/>
      <line y2="360" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="360"/>
      <line y2="391" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="389"/>
      <line y2="390" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="390"/>
      <line y2="421" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="419"/>
      <line y2="420" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="420"/>
      <line y2="451" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="449"/>
      <line y2="450" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="450"/>
      <line y2="481" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="479"/>
      <line y2="480" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="480"/>
      <line y2="511" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="509"/>
      <line y2="510" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="510"/>
      <line y2="541" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="539"/>
      <line y2="540" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="540"/>
      <line y2="571" fill="none" x1="360" clip-path="url(#clipPath1)" x2="360" y1="569"/>
      <line y2="570" fill="none" x1="359" clip-path="url(#clipPath1)" x2="361" y1="570"/>
      <line y2="-29" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="-31"/>
      <line y2="-30" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="-30"/>
      <line y2="1" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="-1"/>
      <line y2="0" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="0"/>
      <line y2="31" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="29"/>
      <line y2="30" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="30"/>
      <line y2="61" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="59"/>
      <line y2="60" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="60"/>
      <line y2="91" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="89"/>
      <line y2="90" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="90"/>
      <line y2="121" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="119"/>
      <line y2="120" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="120"/>
      <line y2="151" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="149"/>
      <line y2="150" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="150"/>
      <line y2="181" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="179"/>
      <line y2="180" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="180"/>
      <line y2="211" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="209"/>
      <line y2="210" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="210"/>
      <line y2="241" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="239"/>
      <line y2="240" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="240"/>
      <line y2="271" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="269"/>
      <line y2="270" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="270"/>
      <line y2="301" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="299"/>
      <line y2="300" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="300"/>
      <line y2="331" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="329"/>
      <line y2="330" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="330"/>
      <line y2="361" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="359"/>
      <line y2="360" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="360"/>
      <line y2="391" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="389"/>
      <line y2="390" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="390"/>
      <line y2="421" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="419"/>
      <line y2="420" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="420"/>
      <line y2="451" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="449"/>
      <line y2="450" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="450"/>
      <line y2="481" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="479"/>
      <line y2="480" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="480"/>
      <line y2="511" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="509"/>
      <line y2="510" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="510"/>
      <line y2="541" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="539"/>
      <line y2="540" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="540"/>
      <line y2="571" fill="none" x1="390" clip-path="url(#clipPath1)" x2="390" y1="569"/>
      <line y2="570" fill="none" x1="389" clip-path="url(#clipPath1)" x2="391" y1="570"/>
      <line y2="-29" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="-31"/>
      <line y2="-30" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="-30"/>
      <line y2="1" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="-1"/>
      <line y2="0" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="0"/>
      <line y2="31" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="29"/>
      <line y2="30" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="30"/>
      <line y2="61" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="59"/>
      <line y2="60" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="60"/>
      <line y2="91" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="89"/>
      <line y2="90" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="90"/>
      <line y2="121" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="119"/>
      <line y2="120" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="120"/>
      <line y2="151" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="149"/>
      <line y2="150" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="150"/>
      <line y2="181" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="179"/>
      <line y2="180" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="180"/>
      <line y2="211" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="209"/>
      <line y2="210" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="210"/>
      <line y2="241" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="239"/>
      <line y2="240" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="240"/>
      <line y2="271" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="269"/>
      <line y2="270" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="270"/>
      <line y2="301" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="299"/>
      <line y2="300" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="300"/>
      <line y2="331" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="329"/>
      <line y2="330" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="330"/>
      <line y2="361" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="359"/>
      <line y2="360" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="360"/>
      <line y2="391" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="389"/>
      <line y2="390" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="390"/>
      <line y2="421" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="419"/>
      <line y2="420" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="420"/>
      <line y2="451" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="449"/>
      <line y2="450" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="450"/>
      <line y2="481" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="479"/>
      <line y2="480" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="480"/>
      <line y2="511" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="509"/>
      <line y2="510" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="510"/>
      <line y2="541" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="539"/>
      <line y2="540" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="540"/>
      <line y2="571" fill="none" x1="420" clip-path="url(#clipPath1)" x2="420" y1="569"/>
      <line y2="570" fill="none" x1="419" clip-path="url(#clipPath1)" x2="421" y1="570"/>
      <line y2="-29" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="-31"/>
      <line y2="-30" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="-30"/>
      <line y2="1" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="-1"/>
      <line y2="0" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="0"/>
      <line y2="31" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="29"/>
      <line y2="30" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="30"/>
      <line y2="61" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="59"/>
      <line y2="60" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="60"/>
      <line y2="91" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="89"/>
      <line y2="90" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="90"/>
      <line y2="121" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="119"/>
      <line y2="120" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="120"/>
      <line y2="151" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="149"/>
      <line y2="150" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="150"/>
      <line y2="181" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="179"/>
      <line y2="180" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="180"/>
      <line y2="211" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="209"/>
      <line y2="210" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="210"/>
      <line y2="241" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="239"/>
      <line y2="240" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="240"/>
      <line y2="271" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="269"/>
      <line y2="270" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="270"/>
      <line y2="301" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="299"/>
      <line y2="300" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="300"/>
      <line y2="331" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="329"/>
      <line y2="330" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="330"/>
      <line y2="361" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="359"/>
      <line y2="360" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="360"/>
      <line y2="391" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="389"/>
      <line y2="390" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="390"/>
      <line y2="421" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="419"/>
      <line y2="420" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="420"/>
      <line y2="451" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="449"/>
      <line y2="450" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="450"/>
      <line y2="481" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="479"/>
      <line y2="480" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="480"/>
      <line y2="511" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="509"/>
      <line y2="510" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="510"/>
      <line y2="541" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="539"/>
      <line y2="540" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="540"/>
      <line y2="571" fill="none" x1="450" clip-path="url(#clipPath1)" x2="450" y1="569"/>
      <line y2="570" fill="none" x1="449" clip-path="url(#clipPath1)" x2="451" y1="570"/>
      <line y2="-29" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="-31"/>
      <line y2="-30" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="-30"/>
      <line y2="1" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="-1"/>
      <line y2="0" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="0"/>
      <line y2="31" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="29"/>
      <line y2="30" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="30"/>
      <line y2="61" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="59"/>
      <line y2="60" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="60"/>
      <line y2="91" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="89"/>
      <line y2="90" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="90"/>
      <line y2="121" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="119"/>
      <line y2="120" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="120"/>
      <line y2="151" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="149"/>
      <line y2="150" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="150"/>
      <line y2="181" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="179"/>
      <line y2="180" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="180"/>
      <line y2="211" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="209"/>
      <line y2="210" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="210"/>
      <line y2="241" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="239"/>
      <line y2="240" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="240"/>
      <line y2="271" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="269"/>
      <line y2="270" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="270"/>
      <line y2="301" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="299"/>
      <line y2="300" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="300"/>
      <line y2="331" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="329"/>
      <line y2="330" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="330"/>
      <line y2="361" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="359"/>
      <line y2="360" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="360"/>
      <line y2="391" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="389"/>
      <line y2="390" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="390"/>
      <line y2="421" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="419"/>
      <line y2="420" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="420"/>
      <line y2="451" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="449"/>
      <line y2="450" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="450"/>
      <line y2="481" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="479"/>
      <line y2="480" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="480"/>
      <line y2="511" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="509"/>
      <line y2="510" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="510"/>
      <line y2="541" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="539"/>
      <line y2="540" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="540"/>
      <line y2="571" fill="none" x1="480" clip-path="url(#clipPath1)" x2="480" y1="569"/>
      <line y2="570" fill="none" x1="479" clip-path="url(#clipPath1)" x2="481" y1="570"/>
      <line y2="-29" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="-31"/>
      <line y2="-30" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="-30"/>
      <line y2="1" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="-1"/>
      <line y2="0" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="0"/>
      <line y2="31" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="29"/>
      <line y2="30" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="30"/>
      <line y2="61" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="59"/>
      <line y2="60" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="60"/>
      <line y2="91" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="89"/>
      <line y2="90" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="90"/>
      <line y2="121" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="119"/>
      <line y2="120" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="120"/>
      <line y2="151" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="149"/>
      <line y2="150" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="150"/>
      <line y2="181" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="179"/>
      <line y2="180" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="180"/>
      <line y2="211" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="209"/>
      <line y2="210" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="210"/>
      <line y2="241" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="239"/>
      <line y2="240" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="240"/>
      <line y2="271" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="269"/>
      <line y2="270" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="270"/>
      <line y2="301" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="299"/>
      <line y2="300" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="300"/>
      <line y2="331" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="329"/>
      <line y2="330" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="330"/>
      <line y2="361" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="359"/>
      <line y2="360" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="360"/>
      <line y2="391" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="389"/>
      <line y2="390" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="390"/>
      <line y2="421" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="419"/>
      <line y2="420" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="420"/>
      <line y2="451" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="449"/>
      <line y2="450" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="450"/>
      <line y2="481" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="479"/>
      <line y2="480" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="480"/>
      <line y2="511" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="509"/>
      <line y2="510" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="510"/>
      <line y2="541" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="539"/>
      <line y2="540" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="540"/>
      <line y2="571" fill="none" x1="510" clip-path="url(#clipPath1)" x2="510" y1="569"/>
      <line y2="570" fill="none" x1="509" clip-path="url(#clipPath1)" x2="511" y1="570"/>
      <line y2="-29" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="-31"/>
      <line y2="-30" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="-30"/>
      <line y2="1" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="-1"/>
      <line y2="0" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="0"/>
      <line y2="31" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="29"/>
      <line y2="30" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="30"/>
      <line y2="61" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="59"/>
      <line y2="60" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="60"/>
      <line y2="91" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="89"/>
      <line y2="90" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="90"/>
      <line y2="121" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="119"/>
      <line y2="120" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="120"/>
      <line y2="151" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="149"/>
      <line y2="150" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="150"/>
      <line y2="181" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="179"/>
      <line y2="180" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="180"/>
      <line y2="211" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="209"/>
      <line y2="210" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="210"/>
      <line y2="241" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="239"/>
      <line y2="240" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="240"/>
      <line y2="271" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="269"/>
      <line y2="270" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="270"/>
      <line y2="301" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="299"/>
      <line y2="300" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="300"/>
      <line y2="331" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="329"/>
      <line y2="330" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="330"/>
      <line y2="361" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="359"/>
      <line y2="360" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="360"/>
      <line y2="391" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="389"/>
      <line y2="390" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="390"/>
      <line y2="421" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="419"/>
      <line y2="420" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="420"/>
      <line y2="451" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="449"/>
      <line y2="450" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="450"/>
      <line y2="481" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="479"/>
      <line y2="480" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="480"/>
      <line y2="511" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="509"/>
      <line y2="510" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="510"/>
      <line y2="541" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="539"/>
      <line y2="540" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="540"/>
      <line y2="571" fill="none" x1="540" clip-path="url(#clipPath1)" x2="540" y1="569"/>
      <line y2="570" fill="none" x1="539" clip-path="url(#clipPath1)" x2="541" y1="570"/>
    </g>
    <g fill="rgb(255,204,0)" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke="rgb(255,204,0)">
      <rect x="75" width="30" height="30" y="165" clip-path="url(#clipPath2)" stroke="none"/>
    </g>
    <g text-rendering="geometricPrecision" stroke-miterlimit="1.45" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke-linecap="butt">
      <rect fill="none" x="75" width="30" height="30" y="165" clip-path="url(#clipPath2)"/>
      <text x="82.6611" xml:space="preserve" y="184.7139" clip-path="url(#clipPath2)" font-family="sans-serif" stroke="none">X1</text>
    </g>
    <g fill="rgb(255,204,0)" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke="rgb(255,204,0)">
      <rect x="209" width="30" height="30" y="555" clip-path="url(#clipPath2)" stroke="none"/>
    </g>
    <g text-rendering="geometricPrecision" stroke-miterlimit="1.45" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke-linecap="butt">
      <rect fill="none" x="209" width="30" height="30" y="555" clip-path="url(#clipPath2)"/>
      <text x="219.998" xml:space="preserve" y="574.7139" clip-path="url(#clipPath2)" font-family="sans-serif" stroke="none">Y</text>
    </g>
    <g fill="rgb(255,204,0)" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke="rgb(255,204,0)">
      <rect x="255" width="30" height="30" y="345" clip-path="url(#clipPath2)" stroke="none"/>
    </g>
    <g text-rendering="geometricPrecision" stroke-miterlimit="1.45" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke-linecap="butt">
      <rect fill="none" x="255" width="30" height="30" y="345" clip-path="url(#clipPath2)"/>
      <text x="262.6611" xml:space="preserve" y="364.7139" clip-path="url(#clipPath2)" font-family="sans-serif" stroke="none">X2</text>
    </g>
    <g fill="rgb(255,204,0)" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke="rgb(255,204,0)">
      <rect x="356" width="30" height="30" y="298" clip-path="url(#clipPath2)" stroke="none"/>
    </g>
    <g text-rendering="geometricPrecision" stroke-miterlimit="1.45" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke-linecap="butt">
      <rect fill="none" x="356" width="30" height="30" y="298" clip-path="url(#clipPath2)"/>
      <text x="367.335" xml:space="preserve" y="317.7139" clip-path="url(#clipPath2)" font-family="sans-serif" stroke="none">Z</text>
    </g>
    <g fill="rgb(255,204,0)" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke="rgb(255,204,0)">
      <circle r="15" clip-path="url(#clipPath2)" cx="300" cy="90" stroke="none"/>
    </g>
    <g text-rendering="geometricPrecision" stroke-miterlimit="1.45" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke-linecap="butt">
      <circle fill="none" r="15" clip-path="url(#clipPath2)" cx="300" cy="90"/>
      <text x="292.3301" xml:space="preserve" y="94.7139" clip-path="url(#clipPath2)" font-family="sans-serif" stroke="none">U1</text>
    </g>
    <g fill="rgb(255,204,0)" text-rendering="geometricPrecision" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke="rgb(255,204,0)">
      <circle r="15" clip-path="url(#clipPath2)" cx="540" cy="253" stroke="none"/>
    </g>
    <g text-rendering="geometricPrecision" stroke-miterlimit="1.45" shape-rendering="geometricPrecision" transform="matrix(1,0,0,1,-60,-60)" stroke-linecap="butt">
      <circle fill="none" r="15" clip-path="url(#clipPath2)" cx="540" cy="253"/>
      <text x="532.3301" xml:space="preserve" y="257.7139" clip-path="url(#clipPath2)" font-family="sans-serif" stroke="none">U2</text>
      <path fill="none" d="M95.1538 195 L216.2466 547.4341" clip-path="url(#clipPath2)"/>
      <path d="M218.8462 555 L219.6755 542.0265 L215.9216 546.4884 L210.2182 545.2759 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" d="M105 195 L249.3431 339.3431" clip-path="url(#clipPath2)"/>
      <path d="M255 345 L250.0502 332.9792 L248.636 338.636 L242.9792 340.0503 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" d="M266.7143 375 L228.9975 547.1853" clip-path="url(#clipPath2)"/>
      <path d="M227.2857 555 L234.7376 544.3478 L229.2115 546.2084 L224.9692 542.2081 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" d="M105 187.0996 L348.769 302.4779" clip-path="url(#clipPath2)"/>
      <path d="M356 305.9004 L347.2926 296.2473 L347.8652 302.0501 L343.0145 305.286 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" d="M356 319.9802 L292.2531 349.6446" clip-path="url(#clipPath2)"/>
      <path d="M285 353.0198 L297.9892 352.4902 L293.1598 349.2227 L293.7702 343.4238 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" stroke-dasharray="6,2" d="M286.2128 95.9088 L112.3532 170.4201" clip-path="url(#clipPath2)" stroke="red"/>
      <path fill="red" stroke-dasharray="6,2" d="M105 173.5714 L117.9993 173.4401 L113.2723 170.0262 L114.0601 164.2487 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" stroke-dasharray="6,2" d="M304.5507 104.293 L363.7972 290.377" clip-path="url(#clipPath2)" stroke="red"/>
      <path fill="red" stroke-dasharray="6,2" d="M366.2242 298 L367.348 285.0487 L363.4938 289.4242 L357.8193 288.0825 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" stroke-dasharray="6,2" d="M105 182.4333 L517.2968 249.317" clip-path="url(#clipPath2)" stroke="red"/>
      <path fill="red" stroke-dasharray="6,2" d="M525.1936 250.5981 L514.1491 243.741 L516.3098 249.1569 L512.5478 253.612 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" stroke-dasharray="6,2" d="M529.4102 263.6234 L244.6006 549.3342" clip-path="url(#clipPath2)" stroke="red"/>
      <path fill="red" stroke-dasharray="6,2" d="M238.9527 555 L250.9657 550.0312 L245.3066 548.626 L243.8834 542.9714 Z" clip-path="url(#clipPath2)" stroke="none"/>
      <path fill="none" stroke-dasharray="6,2" d="M525.8644 258.0186 L393.539 304.998" clip-path="url(#clipPath2)" stroke="red"/>
      <path fill="red" stroke-dasharray="6,2" d="M386 307.6746 L398.9813 308.3716 L394.4813 304.6634 L395.6356 298.9478 Z" clip-path="url(#clipPath2)" stroke="none"/>
    </g>
  </g>
</svg>

```


```{r}
svgPanZoom::svgPanZoom(text)
```



